---
title: "SK-Ana Report"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output:
  html_document:
    fig_height: 5
    fig_width: 10
    number_sections: yes
    theme: cerulean
    toc: true
  pdf_document:
    fig_height: 5
    fig_width: 7
    number_sections: yes
    toc: true
  word_document:
    fig_height: 5
    fig_width: 7
    toc: true
fontsize: 11pt
---

```{r init, results='asis', echo=FALSE}

knitr::opts_chunk$set(error = TRUE) 

cat('# Project name :',input$projectTag)
cex=1
mar=c(4,4,2,1)
mgp=c(2,.75,0)
pty='s'
tcl=-0.5
scale = 0.5 # for multiplots
```

__Data file(s)__ :`r Inputs$fileOrig`

## Selected data

__Wavelength range__ : `r signif(range(Inputs$wavl),3)`

__Delay range__ : `r signif(range(Inputs$delay),3)`

```{r image, echo=FALSE}
par(
  cex = cex, cex.main = cex, mar = mar,
  mgp = mgp, tcl = tcl, pty = pty
)
plotImage(Inputs$delay,Inputs$wavl,Inputs$mat)
```

```{r svd, results='asis', echo=FALSE}
if('SVD' %in% input$inReport){
  cat ('# Singular Values Decomposition')
  s<-doSVD()
  if (!is.null(s))
    CS = reshapeCS(s$u,s$v,ncol(s$u))
}
```

```{r svd2, echo=FALSE}
if('SVD' %in% input$inReport) {
  if (!is.null(s)){
    mat <- Inputs$mat
    # Suppress masked areas
    mat <- mat[!is.na(Inputs$delayMask), ]
    mat <- mat[, !is.na(Inputs$wavlMask) ]
    plotSvdLof(s,mat,cex=scale)
  }
}
```

```{r svd3, echo=FALSE}
if('SVD' %in% input$inReport) {
  if (!is.null(s))
    plotSVDVecBloc(CS$C,CS$S,Inputs$delay,Inputs$wavl,cex=scale)    
}
```

```{r als, results='asis', echo=FALSE}
if ('ALS' %in% input$inReport) {
  cat("# ALS Decomposition\n\n")
  if (!is.null(alsOut <- resALS$results)) {
    cat("__Number of components__ : ", input$nALS, "\n\n")
    cat("__Results__ after ", alsOut$iter, " iterations\n\n")
    cat(alsOut$msg)
    CS <- reshapeCS(alsOut$C, alsOut$S, ncol(alsOut$C))
  }
}
```

```{r als2, results='asis', echo=FALSE}
if('ALS' %in% input$inReport)
  if (!is.null(alsOut))
    cat ('## Spectra and Kinetics')
```

```{r als3, echo=FALSE}
if('ALS' %in% input$inReport) {
  if (!is.null(alsOut)){
    par(mfrow=c(1,2))
    plotAlsVec(alsOut,type="Sp" ,cex=scale)
    plotAlsVec(alsOut,type="Kin",cex=scale)
  }
}
```

```{r als4, results='asis', echo=FALSE}
if('ALS' %in% input$inReport)
   if (!is.null(alsOut))
     cat ('## Residuals')
```

```{r als5, echo=FALSE}
if('ALS' %in% input$inReport) 
  if (!is.null(alsOut))
    plotResid(Inputs$delay,Inputs$wavl,Inputs$mat,CS$C,CS$S,cex=scale)
```

```{r als6, results='asis', echo=FALSE}
if('ALS' %in% input$inReport)
   if (!is.null(alsOut))
     cat ('## Contributions')
```

```{r als7, echo=FALSE, fig.height=7}
if('ALS' %in% input$inReport)
  if (!is.null(alsOut))
    plotConbtribs(Inputs$delay,Inputs$wavl,Inputs$mat,CS$C,CS$S,cex=scale)
```

```{r als8, results='asis', echo=FALSE}
if('ALS' %in% input$inReport)
   if (!is.null(alsOut) & !is.null(resAmb$results))
     cat ('## Ambiguity')
```

```{r als9, echo=FALSE, fig.height=5}
if('ALS' %in% input$inReport) {
  if (!is.null(alsOut) & !is.null(resAmb$results)) {
    par(mfrow = c(1,2))
    plotAmbVec(
      alsOut <- doALS(), 
      resAmb$results$solutions,
      type = "Sp",
      displayLines = input$ambDisplayLines,
      xlim = rangesAmbSp$x,
      ylim = rangesAmbSp$y,
      delayTrans = Inputs$delayTrans,
      cex = scale
    )
    plotAmbVec(
      alsOut <- doALS(), 
      resAmb$results$solutions,
      type = "Kin",
      displayLines = input$ambDisplayLines,
      xlim = rangesAmbKin$x,
      ylim = rangesAmbKin$y,
      delayTrans = Inputs$delayTrans,
      cex = scale
    )
  }
}
```

```{r kin, results='asis', echo=FALSE}
if ('KIN' %in% input$inReport)
  cat('# Kinetic modeling')

```

```{r kincs, results='asis', echo=FALSE}
if ('KIN' %in% input$inReport)
  cat('## Chemical scheme and initial parameters values')
```

```{r kincs.1, results='asis', comment='',echo=FALSE}
if ('KIN' %in% input$inReport) {
  cat(paste(Scheme$scheme, collapse = '\n\n')) 
}
```

```{r kinop, results='asis', echo=FALSE}
if ('KIN' %in% input$inReport) 
  if (!is.null(kinOut <-resLoc$results))
    cat('## Optimization')
```

```{r kinop.1, results='markup', comment='', echo=FALSE}
if ('KIN' %in% input$inReport) {
  if (!is.null(kinOut <-resLoc$results)) {
    if(!is.null(resGlob$results)) {
      cat('GLOBAL OPTIMIZATION:\n')
      cat(stdGlobOut(), sep = '\n')
      cat('\n')
    }
    cat('LOCAL OPTIMIZATION:\n')
    cat(stdLocOut(), sep = '\n')
    cat('\n')
    if (kinOut$cnv != 0) {
      cat('WARNING: Optimization ended badly !\n')
    }
  }
}
```

```{r kinop.2, results = 'asis', echo=FALSE}
if ('KIN' %in% input$inReport) {
  if (!is.null(kinOut <-resLoc$results)) {
    cat('## Optimal parameters\n\n')
    paropt <- kinOut$paropt
    map <- parExpand(kinOut$map, paropt)
    names(map) <- names(paropt)
    
    Sigma <- try(solve(kinOut$hessian), silent = TRUE)
    if (class(Sigma) != "try-error" && kinOut$cnv == 0) {
      EV <- Re(eigen(Sigma)$values)
      if (sum(EV < 0) > 0) print("Non-positive definite Covariance matrix")
      Sd <- diag(Sigma)^0.5
      names(Sd) <- names(paropt)
    } else {
      Sd <- rep(NA, length(paropt))
      names(Sd) <- names(paropt)
    }
    lSd <- unlist(sdExpand(Sd, paropt))
    names(lSd) <- names(paropt)
    
    eps <- 1e-3
    parsc <- parContract(paropt)
    LB <- parsc$LB
    names(LB) <- parsc$names
    UB <- parsc$UB
    names(UB) <- parsc$names
    nPar <- length(names(map))
    alert <- rep("", nPar)
    names(alert) <- names(map)
    tags <- rep("", nPar)
    names(tags) <- names(map)
    val <- rep(NA, nPar)
    names(val) <- names(map)
    valF <- rep(NA, nPar)
    names(valF) <- names(map)
    
    for (item in names(map)) {
      # Detect params close to priors limits
      if (abs(kinOut$map[item] - LB[item]) < eps) {
        alert[item] <- " *** at min of prior"
      } else if (abs(kinOut$map[item] - UB[item]) < eps) {
        alert[item] <- " *** at max of prior"
      }
      
      if (grepl("log", item)) {
      tags[item] <- sub("log", "", item)
      val[item] <- signif(exp(map[[item]]), digits = 2)
      valF[item] <- ifelse(
        !is.finite(lSd[item]),
        "",
        paste(signif(100*lSd[item], digits = 3),' %')
      )
    } else {
      tags[item] <- item
      val[item] <- signif(map[item], digits = 2)
      valF[item] <- ifelse(
        !is.finite(lSd[item]),
        "",
        signif(lSd[item], digits = 3)
      )
    }
    }
    
    knitr::kable(
      data.frame(
        Name = tags,
        Value = val,
        Uncert = valF,
        Comment = alert
      ),
      row.names = FALSE
    )
  }
}
```

```{r kinLOF, results='asis', echo=FALSE}
if('KIN' %in% input$inReport)
  if (!is.null(opt <-resLoc$results))
    cat ('## L.o.f. vs. SVD and Integrated Kinetics')
```

```{r kinLOF.1, echo=FALSE}
if('KIN' %in% input$inReport)
  if (!is.null(opt <-resLoc$results)) {
    plotLofVsSvd(s <- doSVD(), opt)
    plotIntKin(opt)
  }
```

```{r kinPD, results='asis', echo=FALSE}
if('KIN' %in% input$inReport)
  if (!is.null(opt <-resLoc$results))
    cat ('## Parameters densities')
```

```{r kinPD.1, echo=FALSE}
if('KIN' %in% input$inReport)
  if (!is.null(opt <-resLoc$results))
    plotPriPost(opt)
```

```{r kinRes, results='asis', echo=FALSE}
if('KIN' %in% input$inReport)
    if (!is.null(opt <-resLoc$results))
      cat ('## Residuals')
```

```{r kinRes.1, echo=FALSE}
if('KIN' %in% input$inReport) {
  if (!is.null(opt <-resLoc$results)) {
    CS <- reshapeCS(opt$C, opt$S)
    plotResid(Inputs$delay,Inputs$wavl,Inputs$mat,CS$C,CS$S,cex=scale)
    plotResidAna(Inputs$delay,Inputs$wavl,Inputs$mat,CS$C,CS$S,cex=scale)
  }
}
```

```{r kinSC, results='asis', echo=FALSE}
if('KIN' %in% input$inReport)
  if (!is.null(opt <-resLoc$results))
    cat ('## Spectra and Kinetics')

```

```{r kinSC.1, echo=FALSE}
if('KIN' %in% input$inReport) {
  if (!is.null(opt <-resLoc$results)) {
    par(mfrow=c(1,2))
    plotAlsVec(opt,type="Sp" ,cex=scale)
    plotAlsVec(opt,type="Kin",cex=scale)
  }
}
```

```{r kinCont, results='asis', echo=FALSE}
if('KIN' %in% input$inReport)
  if (!is.null(opt <-resLoc$results))
    cat ('## Contributions')
```

```{r kinCont.1, echo=FALSE, fig.height=7}
if('KIN' %in% input$inReport)
  if (!is.null(opt <-resLoc$results)){
    CS <- reshapeCS(opt$C, opt$S)
    plotConbtribs(Inputs$delay,Inputs$wavl,Inputs$mat,CS$C,CS$S)
  }
```


******

# Session Info

```{r, echo=FALSE}
sessionInfo()
```
