wellPanel(
  fluidRow(
           verbatimTextOutput('kinGlPrint'),
           verbatimTextOutput('kinOptPrint')
  ),
  fluidRow(
    column(4,
           uiOutput('kinRes')
    ),
    column(6,
           DT::dataTableOutput('kinOpt')
    )
  )
)
